---
workspace:
  base: /go
  path: src/github.com/NYTimes/drone-gke

branches: "0.4-istio-dev"

pipeline:
  test:
    image: golang:1.8
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -a -ldflags "-X main.rev=${DRONE_COMMIT}"

  publish_istio:
    image: plugins/docker
    repo: nytimes/drone-gke
    tag:
      - "0.4-istio-dev"
    secrets:
      - docker_username
      - docker_password
    when:
      event: push
