---
workspace:
  base: /go
  path: src/github.com/NYTimes/drone-gke

branches: "0.4.x"

pipeline:
  test:
    image: golang:1.8
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      
  build:
    image: golang:1.8
    environment:
      - CGO_ENABLED=0
    commands:
      - go build -a -ldflags "-X main.rev=${DRONE_COMMIT}"

  publish:
    image: plugins/docker
    repo: nytimes/drone-gke
    tag:
      - "0.4"
    secrets:
      - docker_username
      - docker_password
    when:
      event: push

  slack:
    image: plugins/slack
    channel: dv-notifications
    secrets:
      - slack_webhook
